version: '3.1'
services:
  db:
    container_name: auction-db
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auction
  redis:
    container_name: auction-redis
    command: redis-server --requirepass password
    image: redis:alpine
    ports:
      - 6379:6379
