version: '3.1'
services:
  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auction
  test_db:
    image: postgres:10-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user_test
      POSTGRES_PASSWORD: password_test
      POSTGRES_DB: auction_test
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  redis:
    container_name: auction-redis
    image: redis:alpine
    ports:
      - 6379:6379
  redis-commander:
    container_name: auction-redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

